import { createFileRoute } from "@tanstack/react-router";
import { DetailGrid,PageIntro,Section,Status } from "../components/portfolio/site";
export const Route=createFileRoute("/projects")({head:()=>({meta:[{title:"Projects — Muhammad Shammas N"},{name:"description",content:"Beginner cybersecurity projects covering Python, Linux, and controlled virtual laboratories."},{property:"og:title",content:"Cybersecurity Projects"},{property:"og:description",content:"Practical learning projects with objectives, methods, limitations, and future improvements."}],links:[{rel:"canonical",href:"/projects"}]}),component:Projects});
const projects=[
 {title:"Python Mini Firewall",desc:"A beginner cybersecurity project developed in Python to explore rule-based traffic filtering and security logic.",status:"In development",items:[{label:"Problem",value:"Understanding how explicit rules can permit or reject traffic."},{label:"Objective",value:"Explore rule-based filtering and basic security decision logic."},{label:"Environment",value:"Local educational Python environment."},{label:"Technologies",value:"Python"},{label:"Methodology",value:"Define simple rules, process inputs, and observe outcomes."},{label:"Results",value:"Learning artifact; technical results will be documented as development continues."},{label:"What I learned",value:"Program flow, conditions, and translating security rules into code."},{label:"Limitations",value:"A learning model, not a production network firewall."},{label:"Future improvements",value:"Improve rule handling, validation, logging, and documentation."}]},
 {title:"Linux Security Laboratory",desc:"Hands-on Linux practice focused on command-line skills, file systems, permissions, navigation, and security-oriented system understanding.",status:"Ongoing",items:[{label:"Problem",value:"Developing confident Linux system navigation and permission awareness."},{label:"Objective",value:"Build practical command-line and system foundations."},{label:"Environment",value:"OverTheWire and local educational systems."},{label:"Technologies",value:"Linux • Shell • OverTheWire"},{label:"Methodology",value:"Guided challenges, command practice, and documented observations."},{label:"Results",value:"Ongoing development of foundational Linux fluency."},{label:"What I learned",value:"Navigation, files, permissions, users, processes, and basic system behaviour."},{label:"Limitations",value:"Educational exercises rather than production administration."},{label:"Future improvements",value:"Expand into services, logs, hardening, and scripting."}]},
 {title:"Virtual Cybersecurity Laboratory",desc:"A controlled virtual environment for studying networking, security testing, attack/defence concepts, and system behaviour.",status:"In development",items:[{label:"Problem",value:"Security concepts require a safe place for practical observation."},{label:"Objective",value:"Create an isolated environment for authorized educational practice."},{label:"Environment",value:"Controlled virtual machines and isolated networking."},{label:"Technologies",value:"VMware • Kali Linux • networking tools"},{label:"Methodology",value:"Build, isolate, observe, document, and reset laboratory systems."},{label:"Results",value:"A developing environment for structured practical study."},{label:"What I learned",value:"Virtualization, network setup, isolation, and responsible laboratory practice."},{label:"Limitations",value:"Activities are educational and do not represent professional assessments."},{label:"Future improvements",value:"Add repeatable lab notes, traffic analysis, and defensive exercises."}]}
];
function Projects(){return <><PageIntro eyebrow="Projects" title="Practical work, documented honestly."><p>Learning projects are presented with their context, methods, limitations, and next steps—not as finished professional work.</p></PageIntro>{projects.map((p,i)=><Section key={p.title} title={p.title} eyebrow={`Project ${String(i+1).padStart(2,"0")}`}><div className="mb-7 flex flex-col items-start justify-between gap-5 sm:flex-row"><p className="max-w-3xl text-base leading-7 text-muted-foreground">{p.desc}</p><Status>{p.status}</Status></div><DetailGrid items={p.items}/><div className="mt-5 flex flex-wrap gap-5 font-mono text-xs text-muted-foreground"><span>GitHub link — placeholder</span><span>Technical write-up — placeholder</span></div></Section>)}<Section title="Future projects" eyebrow="Planned / coming soon"><div className="grid gap-4 sm:grid-cols-3">{["Network Traffic Analysis","Web Security Laboratory","Python Security Tools"].map(x=><div key={x} className="card-lift border border-dashed border-border p-6"><Status>Planned</Status><h3 className="mt-8 font-serif text-xl">{x}</h3><p className="mt-3 text-sm text-muted-foreground">Coming soon</p></div>)}</div></Section></>}
